### ISSUE TITLE
How to blacklist a container?

### ISSUE THREAD

**Issue by Mondrethos** [yuitakaa/InvTweaksReborn#43]
Hi,

I apologize if this is mentioned somewhere else, but how do you blacklist something?

**Comment by benbenlaw** [comment]
yeah would like to know as well

**Comment by aaronhowser1** [comment]
So looks like in the `invtweaks-client.toml`, go down to the `#Custom settings per GUI` section. There are several that are already disabled.

```toml
	[[sorting.containerOverrides]]
		containerClass = "com.tfar.craftingstation.CraftingStationContainer"
		sortRange = ""
```
This means that it can only sort the slots between `null` and `null`, aka none. It doesn't have a way to see the container class, but Quark does in its config: `Print Screen Classnames`
